version: '3'
services:
  nginx-server:
    image: nginx:alpine
    ports:
      - "8083:80"
    container_name: nginx-container
    restart: always

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: livredb
    ports:
      - "3307:3306"
    container_name: mysql-container
    restart: always

  biblio:
    build:
      context: ./biblio
      dockerfile: Dockerfile
    ports:
      - "80:80"

  back-biblio:
    build:
      context: ./back-biblio
      dockerfile: Dockerfile
    ports:
      - "8082:8081"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - biblio
    command: npm run test

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml