# Utiliser une image Node.js
FROM node:14

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le package.json et le package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances Node.js
RUN npm install

# Copier l'ensemble du code source dans le conteneur
COPY . .

# Définir la commande pour démarrer votre application Node.js
CMD ["node", "app.js"]
