global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'add-book-service'
    static_configs:
      - targets: ['add-book-service:5000']

  - job_name: 'read-book-service'
    static_configs:
      - targets: ['read-book-service:5001']

  
  - job_name: 'display-book-service'
    static_configs:
      - targets: ['display-book-service:5002']
