#version: '3'
#  Spécifie la version de fichier Docker Compose.
#services:
#  Une liste des services Docker à créer et à exécuter.
#web:
#  Nom du premier service.
# image: nginx:latest
#  Image Docker à utiliser pour le service.
#ports:
#  Port sur la machine hôte à un port dans le conteneur.
# - "5000:5000"
#  Le port 8080 sur l'hôte au port 80 dans le conteneur.
# build: ./app
#volumes:
# - ./app:/app
#depends_on:
#  - redis-container
#redis-container:
# image: redis

#Ce script est un fichier Docker Compose qui décrit deux services qui seront exécutés dans des conteneurs Docker: 
#un service Web et un service Redis.

version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 55432:5432
    networks:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
