name: Hello

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build && npm run test

      - name: Health Check
        run: |
          if docker ps --filter "name=h3_microservice-biblio" --filter "name=h3_microservice-back-biblio" | grep -q "Up"; then
            echo "All containers are running"
            exit 0
          else
            echo "One or more containers are not running"
            exit 1
          fi
