name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.marinouh }}
          password: ${{ secrets.dckr_pat_w6Y5IfydAbgvOcVHRyD3zEHExSU }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.marinouh }}/biblio:latest

      - name: Check if container is running
        run: |
          if docker ps -q --filter "name=h3_microservice-back-biblio-1" | grep -q .; then
            echo "Container is running"
          else
            echo "Container is not running"
            exit 1
          fi